language: python
python: 2.7
env:
  - TOX_ENV=nose
  - TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
notifications:
  irc: "chat.freenode.net##d0ugal"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database test_home;' -U postgres
